dtb-$(CONFIG_ARCH_BCM_IPROC) += ns2-a0-svk.dtb ns2-xmc.dtb ns2-cups.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += ns2-svk-d3.dtb ns2-svk-d4.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += pegasus-palladium.dtb pegasus-bcm58543.dtb pegasus-bcm58542.dtb pegasus-bcm58541.dtb pegasus-bcm58540.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += pegasus-bcm58543xmc.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-palladium.dtb stingray-pd-paxc-chimp.dtb stingray-pd-paxb.dtb stingray-pd-usb.dtb
dtb-$(CONFIG_ARCH_BCM_IPROC) += stingray-svk-diag.dtb
dtb-$(CONFIG_ARCH_VULCAN) += vulcan-eval.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
