# PEGASUS Platform Support
snd-soc-pegasus-objs := pegasus-pcm.o
snd-soc-pegasus-ssp-objs := pegasus-ssp.o

obj-$(CONFIG_SND_SOC_PEGASUS) += snd-soc-pegasus.o
obj-$(CONFIG_SND_SOC_PEGASUS_SSP) += snd-soc-pegasus-ssp.o

# For PEGASUS SVK
snd-soc-pegasus-svk-machine-objs := pegasus_svk-machine.o
obj-$(CONFIG_SND_SOC_PEGASUS_AUDIO_MACHINE) += snd-soc-pegasus-svk-machine.o
