/*
 * Copyright (C) 2016, Broadcom Corporation. All Rights Reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef __PEGASUS_PCM_H__
#define __PEGASUS_PCM_H__

/* These are offsets necessary to access the various audio block regs.
 * The names used here are how they appear in the datasheets, etc.
 * Some of these names are very long which makes writing code to fit within
 * the 80 column constraint difficult. Therefore, many of these defines
 * are redefined with shorter versions below, these are the versions
 * we will be using in the code.
 */
#define AUDIO_AUD_INTH_R5F_STATUS_BASE 0x040
#define AUDIO_AUD_INTH_R5F_CLEAR_BASE 0x048
#define AUDIO_AUD_INTH_R5F_MASK_SET_BASE 0x050
#define AUDIO_AUD_INTH_R5F_MASK_CLEAR_BASE 0x054

#define AUDIO_AUD_FMM_BF_CTRL_REARM_FREE_MARK_BASE 0x344
#define AUDIO_AUD_FMM_BF_CTRL_REARM_FULL_MARK_BASE 0x348

/* Ring Buffer Ctrl Regs --- Start */
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_RDADDR_BASE 0x500
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_RDADDR_BASE 0x518
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_RDADDR_BASE 0x530
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_RDADDR_BASE 0x548
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_RDADDR_BASE 0x560
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_RDADDR_BASE 0x578
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_RDADDR_BASE 0x590

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_BASEADDR_BASE 0x508
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_BASEADDR_BASE 0x520
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_BASEADDR_BASE 0x538
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_BASEADDR_BASE 0x550
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_BASEADDR_BASE 0x568
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_BASEADDR_BASE 0x580
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_BASEADDR_BASE 0x598

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_WRADDR_BASE 0x5c4
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_WRADDR_BASE 0x5dc
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_WRADDR_BASE 0x5f4
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_WRADDR_BASE 0x60c
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_WRADDR_BASE 0x624
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_WRADDR_BASE 0x63c

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_RDADDR_BASE 0x5c0
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_RDADDR_BASE 0x5d8
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_RDADDR_BASE 0x5f0
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_RDADDR_BASE 0x608
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_RDADDR_BASE 0x620
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_RDADDR_BASE 0x638

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_ENDADDR_BASE 0x50c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_ENDADDR_BASE 0x524
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_ENDADDR_BASE 0x53c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_ENDADDR_BASE 0x554
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_ENDADDR_BASE 0x56c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_ENDADDR_BASE 0x584
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_ENDADDR_BASE 0x59c

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_ENDADDR_BASE 0x5cc
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_ENDADDR_BASE 0x5e4
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_ENDADDR_BASE 0x5fc
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_ENDADDR_BASE 0x614
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_ENDADDR_BASE 0x62c
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_ENDADDR_BASE 0x644

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_WRADDR_BASE 0x504
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_WRADDR_BASE 0x51c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_WRADDR_BASE 0x534
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_WRADDR_BASE 0x54c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_WRADDR_BASE 0x564
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_WRADDR_BASE 0x57c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_WRADDR_BASE 0x594

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_BASEADDR_BASE 0x640
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_BASEADDR_BASE 0x628
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_BASEADDR_BASE 0x610
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_BASEADDR_BASE 0x5f8
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_BASEADDR_BASE 0x5e0
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_BASEADDR_BASE 0x5c8

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_FREE_MARK_BASE 0x5a0
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_FREE_MARK_BASE 0x588
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_FREE_MARK_BASE 0x570
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_FREE_MARK_BASE 0x558
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_FREE_MARK_BASE 0x540
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_FREE_MARK_BASE 0x528
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_FREE_MARK_BASE 0x510

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_FULL_MARK_BASE 0x5d0
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_FULL_MARK_BASE 0x5e8
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_FULL_MARK_BASE 0x600
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_FULL_MARK_BASE 0x618
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_FULL_MARK_BASE 0x630
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_FULL_MARK_BASE 0x648
/* Ring Buffer Ctrl Regs --- End */

/* Error Status Regs --- Start */
#define AUDIO_AUD_FMM_BF_ESR_ESR0_STATUS_BASE 0x900
#define AUDIO_AUD_FMM_BF_ESR_ESR1_STATUS_BASE 0x918
#define AUDIO_AUD_FMM_BF_ESR_ESR2_STATUS_BASE 0x930
#define AUDIO_AUD_FMM_BF_ESR_ESR3_STATUS_BASE 0x948
#define AUDIO_AUD_FMM_BF_ESR_ESR4_STATUS_BASE 0x960

#define AUDIO_AUD_FMM_BF_ESR_ESR0_STATUS_CLEAR_BASE 0x908
#define AUDIO_AUD_FMM_BF_ESR_ESR1_STATUS_CLEAR_BASE 0x920
#define AUDIO_AUD_FMM_BF_ESR_ESR2_STATUS_CLEAR_BASE 0x938
#define AUDIO_AUD_FMM_BF_ESR_ESR3_STATUS_CLEAR_BASE 0x950
#define AUDIO_AUD_FMM_BF_ESR_ESR4_STATUS_CLEAR_BASE 0x968

#define AUDIO_AUD_FMM_BF_ESR_ESR0_MASK_SET_BASE 0x910
#define AUDIO_AUD_FMM_BF_ESR_ESR1_MASK_SET_BASE 0x928
#define AUDIO_AUD_FMM_BF_ESR_ESR2_MASK_SET_BASE 0x940
#define AUDIO_AUD_FMM_BF_ESR_ESR3_MASK_SET_BASE 0x958
#define AUDIO_AUD_FMM_BF_ESR_ESR4_MASK_SET_BASE 0x970

#define AUDIO_AUD_FMM_BF_ESR_ESR0_MASK_CLEAR_BASE 0x914
#define AUDIO_AUD_FMM_BF_ESR_ESR1_MASK_CLEAR_BASE 0x92c
#define AUDIO_AUD_FMM_BF_ESR_ESR2_MASK_CLEAR_BASE 0x944
#define AUDIO_AUD_FMM_BF_ESR_ESR3_MASK_CLEAR_BASE 0x95c
#define AUDIO_AUD_FMM_BF_ESR_ESR4_MASK_CLEAR_BASE 0x974

#define AUDIO_AUD_FMM_BF_ESR_ESR0_MASK_BASE 0x90c
#define AUDIO_AUD_FMM_BF_ESR_ESR1_MASK_BASE 0x924
#define AUDIO_AUD_FMM_BF_ESR_ESR2_MASK_BASE 0x93c
#define AUDIO_AUD_FMM_BF_ESR_ESR3_MASK_BASE 0x954
#define AUDIO_AUD_FMM_BF_ESR_ESR4_MASK_BASE 0x96c
/* Error Status Regs --- End */

#define INTH_R5F_STATUS_OFFSET          AUDIO_AUD_INTH_R5F_STATUS_BASE
#define INTH_R5F_MASK_SET_OFFSET        AUDIO_AUD_INTH_R5F_MASK_SET_BASE
#define INTH_R5F_CLEAR_OFFSET           AUDIO_AUD_INTH_R5F_CLEAR_BASE
#define INTH_R5F_MASK_CLEAR_OFFSET      AUDIO_AUD_INTH_R5F_MASK_CLEAR_BASE

#define BF_REARM_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_REARM_FREE_MARK_BASE
#define BF_REARM_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_REARM_FULL_MARK_BASE


#define SRC_RBUF_0_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_RDADDR_BASE
#define SRC_RBUF_1_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_RDADDR_BASE
#define SRC_RBUF_2_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_RDADDR_BASE
#define SRC_RBUF_3_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_RDADDR_BASE
#define SRC_RBUF_4_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_RDADDR_BASE
#define SRC_RBUF_5_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_RDADDR_BASE
#define SRC_RBUF_6_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_RDADDR_BASE
#define SRC_RBUF_0_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_BASEADDR_BASE
#define SRC_RBUF_1_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_BASEADDR_BASE
#define SRC_RBUF_2_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_BASEADDR_BASE
#define SRC_RBUF_3_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_BASEADDR_BASE
#define SRC_RBUF_4_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_BASEADDR_BASE
#define SRC_RBUF_5_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_BASEADDR_BASE
#define SRC_RBUF_6_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_BASEADDR_BASE
#define DST_RBUF_0_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_WRADDR_BASE
#define DST_RBUF_1_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_WRADDR_BASE
#define DST_RBUF_2_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_WRADDR_BASE
#define DST_RBUF_3_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_WRADDR_BASE
#define DST_RBUF_4_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_WRADDR_BASE
#define DST_RBUF_5_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_WRADDR_BASE
#define DST_RBUF_0_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_RDADDR_BASE
#define DST_RBUF_1_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_RDADDR_BASE
#define DST_RBUF_2_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_RDADDR_BASE
#define DST_RBUF_3_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_RDADDR_BASE
#define DST_RBUF_4_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_RDADDR_BASE
#define DST_RBUF_5_RDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_RDADDR_BASE
#define SRC_RBUF_0_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_ENDADDR_BASE
#define SRC_RBUF_1_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_ENDADDR_BASE
#define SRC_RBUF_2_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_ENDADDR_BASE
#define SRC_RBUF_3_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_ENDADDR_BASE
#define SRC_RBUF_4_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_ENDADDR_BASE
#define SRC_RBUF_5_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_ENDADDR_BASE
#define SRC_RBUF_6_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_ENDADDR_BASE
#define DST_RBUF_0_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_ENDADDR_BASE
#define DST_RBUF_1_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_ENDADDR_BASE
#define DST_RBUF_2_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_ENDADDR_BASE
#define DST_RBUF_3_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_ENDADDR_BASE
#define DST_RBUF_4_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_ENDADDR_BASE
#define DST_RBUF_5_ENDADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_ENDADDR_BASE
#define SRC_RBUF_0_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_WRADDR_BASE
#define SRC_RBUF_1_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_WRADDR_BASE
#define SRC_RBUF_2_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_WRADDR_BASE
#define SRC_RBUF_3_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_WRADDR_BASE
#define SRC_RBUF_4_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_WRADDR_BASE
#define SRC_RBUF_5_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_WRADDR_BASE
#define SRC_RBUF_6_WRADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_WRADDR_BASE
#define DST_RBUF_5_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_BASEADDR_BASE
#define DST_RBUF_4_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_BASEADDR_BASE
#define DST_RBUF_3_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_BASEADDR_BASE
#define DST_RBUF_2_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_BASEADDR_BASE
#define DST_RBUF_1_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_BASEADDR_BASE
#define DST_RBUF_0_BASEADDR_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_BASEADDR_BASE
#define SRC_RBUF_6_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_FREE_MARK_BASE
#define SRC_RBUF_5_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_FREE_MARK_BASE
#define SRC_RBUF_4_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_FREE_MARK_BASE
#define SRC_RBUF_3_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_FREE_MARK_BASE
#define SRC_RBUF_2_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_FREE_MARK_BASE
#define SRC_RBUF_1_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_FREE_MARK_BASE
#define SRC_RBUF_0_FREE_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_FREE_MARK_BASE
#define DST_RBUF_0_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_FULL_MARK_BASE
#define DST_RBUF_1_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_FULL_MARK_BASE
#define DST_RBUF_2_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_FULL_MARK_BASE
#define DST_RBUF_3_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_FULL_MARK_BASE
#define DST_RBUF_4_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_FULL_MARK_BASE
#define DST_RBUF_5_FULL_MARK_OFFSET \
			AUDIO_AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_FULL_MARK_BASE

#define ESR0_STATUS_OFFSET      AUDIO_AUD_FMM_BF_ESR_ESR0_STATUS_BASE
#define ESR1_STATUS_OFFSET      AUDIO_AUD_FMM_BF_ESR_ESR1_STATUS_BASE
#define ESR2_STATUS_OFFSET      AUDIO_AUD_FMM_BF_ESR_ESR2_STATUS_BASE
#define ESR3_STATUS_OFFSET      AUDIO_AUD_FMM_BF_ESR_ESR3_STATUS_BASE
#define ESR4_STATUS_OFFSET      AUDIO_AUD_FMM_BF_ESR_ESR4_STATUS_BASE
#define ESR0_STATUS_CLR_OFFSET  AUDIO_AUD_FMM_BF_ESR_ESR0_STATUS_CLEAR_BASE
#define ESR1_STATUS_CLR_OFFSET  AUDIO_AUD_FMM_BF_ESR_ESR1_STATUS_CLEAR_BASE
#define ESR2_STATUS_CLR_OFFSET  AUDIO_AUD_FMM_BF_ESR_ESR2_STATUS_CLEAR_BASE
#define ESR3_STATUS_CLR_OFFSET  AUDIO_AUD_FMM_BF_ESR_ESR3_STATUS_CLEAR_BASE
#define ESR4_STATUS_CLR_OFFSET  AUDIO_AUD_FMM_BF_ESR_ESR4_STATUS_CLEAR_BASE
#define ESR0_MASK_SET_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR0_MASK_SET_BASE
#define ESR1_MASK_SET_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR1_MASK_SET_BASE
#define ESR2_MASK_SET_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR2_MASK_SET_BASE
#define ESR3_MASK_SET_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR3_MASK_SET_BASE
#define ESR4_MASK_SET_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR4_MASK_SET_BASE
#define ESR0_MASK_CLR_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR0_MASK_CLEAR_BASE
#define ESR1_MASK_CLR_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR1_MASK_CLEAR_BASE
#define ESR2_MASK_CLR_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR2_MASK_CLEAR_BASE
#define ESR3_MASK_CLR_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR3_MASK_CLEAR_BASE
#define ESR4_MASK_CLR_OFFSET    AUDIO_AUD_FMM_BF_ESR_ESR4_MASK_CLEAR_BASE
#define ESR0_MASK_STATUS_OFFSET AUDIO_AUD_FMM_BF_ESR_ESR0_MASK_BASE
#define ESR1_MASK_STATUS_OFFSET AUDIO_AUD_FMM_BF_ESR_ESR1_MASK_BASE
#define ESR2_MASK_STATUS_OFFSET AUDIO_AUD_FMM_BF_ESR_ESR2_MASK_BASE
#define ESR3_MASK_STATUS_OFFSET AUDIO_AUD_FMM_BF_ESR_ESR3_MASK_BASE
#define ESR4_MASK_STATUS_OFFSET AUDIO_AUD_FMM_BF_ESR_ESR4_MASK_BASE

struct ringbuf_regs {
	unsigned rdaddr;
	unsigned wraddr;
	unsigned baseaddr;
	unsigned endaddr;
	unsigned fmark;   /* freemark for play, fullmark for caputure */
	unsigned period_bytes;
	unsigned buf_size;
};

#define RINGBUF_REG_PLAYBACK(num) ((struct ringbuf_regs) { \
	.rdaddr = SRC_RBUF_ ##num## _RDADDR_OFFSET, \
	.wraddr = SRC_RBUF_ ##num## _WRADDR_OFFSET, \
	.baseaddr = SRC_RBUF_ ##num## _BASEADDR_OFFSET, \
	.endaddr = SRC_RBUF_ ##num## _ENDADDR_OFFSET, \
	.fmark = SRC_RBUF_ ##num## _FREE_MARK_OFFSET, \
	.period_bytes = 0, \
	.buf_size = 0, \
})

#define RINGBUF_REG_CAPTURE(num) ((struct ringbuf_regs)  { \
	.rdaddr = DST_RBUF_ ##num## _RDADDR_OFFSET, \
	.wraddr = DST_RBUF_ ##num## _WRADDR_OFFSET, \
	.baseaddr = DST_RBUF_ ##num## _BASEADDR_OFFSET, \
	.endaddr = DST_RBUF_ ##num## _ENDADDR_OFFSET, \
	.fmark = DST_RBUF_ ##num## _FULL_MARK_OFFSET, \
	.period_bytes = 0, \
	.buf_size = 0, \
})
#endif
