/*
 * Copyright (C) 2016, Broadcom Corporation. All Rights Reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef __PEGASUS_SSP_H__
#define __PEGASUS_SSP_H__

#include "pegasus-pcm.h"

#define PLL_NDIV_FRACT_MAX  (BIT(20)-1)   /* 20 bits max */

#define AUDIO_AUD_MISC_INIT_OFFSET 0x004
#define AUDIO_AUD_MISC_SEROUT_OE_OFFSET 0x01c

#define I2S_OUT_0_FCI_ID 0x180
#define I2S_OUT_1_FCI_ID 0x181
#define I2S_OUT_2_FCI_ID 0x182

#define CRMU_PLL_AON_CTRL_BASE 0x860

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG0_BASE 0x100
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG1_BASE 0x104
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2_BASE 0x108

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CTRL0_BASE 0x130
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CTRL1_BASE 0x134
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CTRL2_BASE 0x138

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG0_BASE 0x148
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG1_BASE 0x14c
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2_BASE 0x150
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG3_BASE 0x154

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL0_BASE 0x1c0
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL1_BASE 0x1c4
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL2_BASE 0x1c8
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL3_BASE 0x1cc

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP0_BASE 0x1fc
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP1_BASE 0x200
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP2_BASE 0x204
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP3_BASE 0x208

#define AUDIO_AUD_FMM_IOP_OUT_I2S_0_STREAM_CFG_0_BASE 0xa00
#define AUDIO_AUD_FMM_IOP_OUT_I2S_0_I2S_CFG_BASE      0xa04
#define AUDIO_AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0_BASE   0xa0c

#define AUDIO_AUD_FMM_IOP_OUT_I2S_1_STREAM_CFG_0_BASE 0xa40
#define AUDIO_AUD_FMM_IOP_OUT_I2S_1_I2S_CFG_BASE      0xa44
#define AUDIO_AUD_FMM_IOP_OUT_I2S_1_MCLK_CFG_0_BASE   0xa4c

#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_BASE 0xa80
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_BASE      0xa84
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0_BASE   0xa8c

#define AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0_BASE     0xac0
#define AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL_BASE       0xac4
#define AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_FORMAT_CFG_BASE 0xadc
#define AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_MCLK_CFG_0_BASE       0xae0

#define AUDIO_AUD_FMM_IOP_PLL_0_MACRO_BASE 0xb10
#define AUDIO_AUD_FMM_IOP_PLL_0_CONTROL_0_BASE 0xb14
#define AUDIO_AUD_FMM_IOP_PLL_0_USER_NDIV_BASE 0xb18
#define AUDIO_AUD_FMM_IOP_PLL_0_USER_MDIV_Ch0_BASE 0xb24
#define AUDIO_AUD_FMM_IOP_PLL_0_USER_MDIV_Ch1_BASE 0xb28
#define AUDIO_AUD_FMM_IOP_PLL_0_USER_MDIV_Ch2_BASE 0xb2c
#define AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_NDIV_BASE 0xb3c
#define AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch0_BASE 0xb48
#define AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch1_BASE 0xb4c
#define AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch2_BASE 0xb50
#define AUDIO_AUD_FMM_IOP_PLL_0_RESET_BASE 0xb7c

#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_BASE 0xba0
#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_RATE_RATIO_BASE 0xba4
#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_SAMPLE_INC_BASE 0xba8
#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_PHASE_INC_BASE 0xbac
#define AUDIO_AUD_FMM_IOP_NCO_1_MCLK_GEN_0_CONTROL_BASE 0xbe0

#define AUDIO_AUD_FMM_IOP_IN_I2S_0_CAP_STREAM_CFG_0_BASE 0xcf0
#define AUDIO_AUD_FMM_IOP_IN_I2S_0_I2S_IN_CFG_BASE       0xcf4
#define AUDIO_AUD_FMM_IOP_IN_I2S_1_CAP_STREAM_CFG_0_BASE 0xd30
#define AUDIO_AUD_FMM_IOP_IN_I2S_1_I2S_IN_CFG_BASE       0xd34
#define AUDIO_AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_BASE 0xd70
#define AUDIO_AUD_FMM_IOP_IN_I2S_2_I2S_IN_CFG_BASE       0xd74

#define AUDIO_AUD_FMM_IOP_PLL_0_PDIV_BASE 0xb64
#define AUD_FMM_IOP_PLL_0_PDIV_BASE AUDIO_AUD_FMM_IOP_PLL_0_PDIV_BASE

/* Bit postion within the various regs */
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0__MCLK_RATE_R 16
#define AUDIO_AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0__PLLCLKSEL_R 0

#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0__GROUP_ID_R 20
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0__CHANNEL_GROUPING_R 24
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0__ENA 31

#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SOURCEFIFO_ENABLE 0
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__BUFFER_PAIR_ENABLE 1
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SAMPLE_CH_MODE 2
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SOURCEFIFO_SIZE_DOUBLE 5
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__NOT_PAUSE_WHEN_EMPTY 10
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SFIFO_START_HALFFULL 13
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__BIT_RESOLUTION_R 20
#define AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__PROCESS_SEQ_ID_VALID 31

#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__CAPTURE_ENABLE 0
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__BUFFER_PAIR_ENABLE 1
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__DESTFIFO_SIZE_DOUBLE 2
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__NOT_PAUSE_WHEN_FULL 11
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__FCI_CAP_ID_R 12
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__CAPTURE_MODE 24
#define AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__PROCESS_SEQ_ID_VALID 31

#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__CLOCK_ENABLE 0
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__DATA_ENABLE 1
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__DATA_ALIGNMENT 6
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__BITS_PER_SLOT 13
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__VALID_SLOT_R 14
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__FSYNC_WIDTH_R 18
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__SCLKS_PER_1FS_DIV32_R 26
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__SLAVE_MODE 30
#define AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__TDM_MODE 31

#define AUDIO_AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0__CAP_ENA 31
#define AUDIO_AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0__CAP_GROUP_ID_R 4

#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_BG 18
#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_LDO 17
#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_PLL 19
#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_ISO_IN 16
#define AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL__DITHER_ENA 3


#define AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0__ENA 31

#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_SAMPLE_INC__NUMERATOR_R 8
#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL__RESET 12
#define AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL__FREE_RUN 4

#define AUDIO_AUD_FMM_IOP_PLL_0_USER_NDIV__NDIV_FRAC_R 10
#define AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_NDIV__NDIV_FRAC_R 10


#define ICFG_PD_MEM_CTRL 0x240
#define ICFG_SP_MEM_CTRL 0x244
#define CRYPTO_SS_SPU0_MDE_RCVPFCCTRL_0 0x28200238
#define ICFG_RF_MEM_CTRL 0x23c

#define ICFG_PD_MEM_CTRL_OVSTB 21
#define ICFG_PD_MEM_CTRL_POWERONIN 3
#define ICFG_PD_MEM_CTRL_POWEROKIN 2
#define ICFG_PD_MEM_CTRL_LVM 1
#define ICFG_PD_MEM_CTRL_ISO 0

#define PD_MEM_CTRL_OVSTB_MASK      (u32)(1 << ICFG_PD_MEM_CTRL_OVSTB)
#define PD_MEM_CTRL_POWERONIN_MASK  (u32)(1 << ICFG_PD_MEM_CTRL_POWERONIN)
#define PD_MEM_CTRL_POWEROKIN_MASK  (u32)(1 << ICFG_PD_MEM_CTRL_POWEROKIN)
#define PD_MEM_CTRL_LVM_MASK        (u32)(1 << ICFG_PD_MEM_CTRL_LVM)
#define PD_MEM_CTRL_ISO_MASK        (u32)(1 << ICFG_PD_MEM_CTRL_ISO)

#define ICFG_SP_MEM_CTRL_OVSTB 18
#define ICFG_SP_MEM_CTRL_POWERONIN 3
#define ICFG_SP_MEM_CTRL_POWEROKIN 2
#define ICFG_SP_MEM_CTRL_LVM 1
#define ICFG_SP_MEM_CTRL_ISO 0

#define SP_MEM_CTRL_OVSTB_MASK      (u32)(1 << ICFG_SP_MEM_CTRL_OVSTB)
#define SP_MEM_CTRL_POWERONIN_MASK  (u32)(1 << ICFG_SP_MEM_CTRL_POWERONIN)
#define SP_MEM_CTRL_POWEROKIN_MASK  (u32)(1 << ICFG_SP_MEM_CTRL_POWEROKIN)
#define SP_MEM_CTRL_LVM_MASK        (u32)(1 << ICFG_SP_MEM_CTRL_LVM)
#define SP_MEM_CTRL_ISO_MASK        (u32)(1 << ICFG_SP_MEM_CTRL_ISO)

#define ICFG_RF_MEM_CTRL_POWERONIN 3
#define ICFG_RF_MEM_CTRL_POWEROKIN 2
#define ICFG_RF_MEM_CTRL_LVM 1
#define ICFG_RF_MEM_CTRL_ISO 0

#define RF_MEM_CTRL_POWERONIN_MASK  (u32)(1 << ICFG_RF_MEM_CTRL_POWERONIN)
#define RF_MEM_CTRL_POWEROKIN_MASK  (u32)(1 << ICFG_RF_MEM_CTRL_POWEROKIN)
#define RF_MEM_CTRL_LVM_MASK        (u32)(1 << ICFG_RF_MEM_CTRL_LVM)
#define RF_MEM_CTRL_ISO_MASK        (u32)(1 << ICFG_RF_MEM_CTRL_ISO)


/* Shortened and standardized register offsets */
#define CRMU_PLL_AON_CTRL_OFFSET                CRMU_PLL_AON_CTRL_BASE

#define AUDIO_MISC_INIT_OFFSET  AUDIO_AUD_MISC_INIT_OFFSET
#define AUDIO_SEROUT_OE_OFFSET  AUDIO_AUD_MISC_SEROUT_OE_OFFSET
#define BF_DST_CFG0_OFFSET      AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG0_BASE
#define BF_DST_CFG1_OFFSET      AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG1_BASE
#define BF_DST_CFG2_OFFSET      AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2_BASE
#define BF_DST_CTRL0_OFFSET     AUDIO_AUD_FMM_BF_CTRL_DESTCH_CTRL0_BASE
#define BF_DST_CTRL1_OFFSET     AUDIO_AUD_FMM_BF_CTRL_DESTCH_CTRL1_BASE
#define BF_DST_CTRL2_OFFSET     AUDIO_AUD_FMM_BF_CTRL_DESTCH_CTRL2_BASE
#define BF_SRC_CFG0_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG0_BASE
#define BF_SRC_CFG1_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG1_BASE
#define BF_SRC_CFG2_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2_BASE
#define BF_SRC_CFG3_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG3_BASE
#define BF_SRC_CTRL0_OFFSET     AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL0_BASE
#define BF_SRC_CTRL1_OFFSET     AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL1_BASE
#define BF_SRC_CTRL2_OFFSET     AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL2_BASE
#define BF_SRC_CTRL3_OFFSET     AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CTRL3_BASE
#define BF_SRC_GRP0_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP0_BASE
#define BF_SRC_GRP1_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP1_BASE
#define BF_SRC_GRP2_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP2_BASE
#define BF_SRC_GRP3_OFFSET      AUDIO_AUD_FMM_BF_CTRL_SOURCECH_GRP3_BASE

#define OUT_I2S_0_CFG_OFFSET    AUDIO_AUD_FMM_IOP_OUT_I2S_0_I2S_CFG_BASE
#define OUT_I2S_1_CFG_OFFSET    AUDIO_AUD_FMM_IOP_OUT_I2S_1_I2S_CFG_BASE
#define OUT_I2S_2_CFG_OFFSET    AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_BASE

#define OUT_I2S_0_MCLK_CFG_OFFSET AUDIO_AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0_BASE
#define OUT_I2S_1_MCLK_CFG_OFFSET AUDIO_AUD_FMM_IOP_OUT_I2S_1_MCLK_CFG_0_BASE
#define OUT_I2S_2_MCLK_CFG_OFFSET AUDIO_AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0_BASE

#define IOP_PLL_0_MACRO_OFFSET      AUDIO_AUD_FMM_IOP_PLL_0_MACRO_BASE
#define IOP_PLL_0_MDIV_Ch0_OFFSET   AUDIO_AUD_FMM_IOP_PLL_0_USER_MDIV_Ch0_BASE
#define IOP_PLL_0_MDIV_Ch1_OFFSET   AUDIO_AUD_FMM_IOP_PLL_0_USER_MDIV_Ch1_BASE
#define IOP_PLL_0_MDIV_Ch2_OFFSET   AUDIO_AUD_FMM_IOP_PLL_0_USER_MDIV_Ch2_BASE

#define IOP_PLL_0_ACTIVE_MDIV_Ch0_OFFSET \
		AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch0_BASE
#define IOP_PLL_0_ACTIVE_MDIV_Ch1_OFFSET \
		AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch1_BASE
#define IOP_PLL_0_ACTIVE_MDIV_Ch2_OFFSET \
		AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch2_BASE
#define IOP_PLL_0_RESET_OFFSET          AUDIO_AUD_FMM_IOP_PLL_0_RESET_BASE
#define IOP_PLL_0_USER_NDIV_OFFSET AUDIO_AUD_FMM_IOP_PLL_0_USER_NDIV_BASE
#define IOP_PLL_0_ACTIVE_NDIV_OFFSET AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_NDIV_BASE
#define IOP_PLL_0_CONTROL_OFFSET AUDIO_AUD_FMM_IOP_PLL_0_CONTROL_0_BASE
#define IOP_NCO_0_CONTROL_OFFSET AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_BASE
#define IOP_NCO_1_CONTROL_OFFSET AUDIO_AUD_FMM_IOP_NCO_1_MCLK_GEN_0_CONTROL_BASE

#define IN_I2S_0_CFG_OFFSET   AUDIO_AUD_FMM_IOP_IN_I2S_0_I2S_IN_CFG_BASE
#define IN_I2S_1_CFG_OFFSET   AUDIO_AUD_FMM_IOP_IN_I2S_1_I2S_IN_CFG_BASE
#define IN_I2S_2_CFG_OFFSET   AUDIO_AUD_FMM_IOP_IN_I2S_2_I2S_IN_CFG_BASE

#define SPDIF_CTRL_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL_BASE
#define SPDIF_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0_BASE
#define SPDIF_FORMAT_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_FORMAT_CFG_BASE
#define SPDIF_MCLK_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_MCLK_CFG_0_BASE

#define IN_I2S_0_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_IN_I2S_0_CAP_STREAM_CFG_0_BASE
#define IN_I2S_1_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_IN_I2S_1_CAP_STREAM_CFG_0_BASE
#define IN_I2S_2_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_BASE

#define OUT_I2S_0_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_I2S_0_STREAM_CFG_0_BASE
#define OUT_I2S_1_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_I2S_1_STREAM_CFG_0_BASE
#define OUT_I2S_2_STREAM_CFG_OFFSET \
			AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_BASE

/* Shortened and standardized register bit definitions */

#define I2S_OUT_MCLKRATE_SHIFT \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0__MCLK_RATE_R
#define I2S_OUT_MCLKRATE_MASK  (0xF << I2S_OUT_MCLKRATE_SHIFT)

#define I2S_OUT_PLLCLKSEL_SHIFT  \
		AUDIO_AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0__PLLCLKSEL_R
#define I2S_OUT_PLLCLKSEL_MASK  (0xF << I2S_OUT_PLLCLKSEL_SHIFT)

#define I2S_OUT_STREAM_ENA \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0__ENA
#define I2S_OUT_STREAM_CFG_GROUP_ID \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0__GROUP_ID_R
#define I2S_OUT_STREAM_CFG_CHANNEL_GROUPING \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0__CHANNEL_GROUPING_R

#define I2S_IN_STREAM_CFG_CAP_ENA \
		AUDIO_AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0__CAP_ENA
#define I2S_IN_STREAM_CFG_0_GROUP_ID \
		AUDIO_AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0__CAP_GROUP_ID_R

#define I2S_OUT_CFGX_CLK_ENA \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__CLOCK_ENABLE
#define I2S_OUT_CFGX_DATA_ENABLE \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__DATA_ENABLE
#define I2S_OUT_CFGX_TDM_MODE \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__TDM_MODE
#define I2S_OUT_CFGX_SLAVE_MODE \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__SLAVE_MODE
#define I2S_OUT_CFGX_FSYNC_WIDTH \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__FSYNC_WIDTH_R
#define I2S_OUT_CFGX_VALID_SLOT \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__VALID_SLOT_R
#define I2S_OUT_CFGX_BITS_PER_SLOT \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__BITS_PER_SLOT
#define I2S_OUT_CFGX_DATA_ALIGNMENT \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__DATA_ALIGNMENT
#define I2S_OUT_CFGX_SCLKS_PER_1FS_DIV32 \
		AUDIO_AUD_FMM_IOP_OUT_I2S_2_I2S_CFG__SCLKS_PER_1FS_DIV32_R

#define BF_SRC_CFGX_BIT_RES \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__BIT_RESOLUTION_R
#define BF_SRC_CFGX_SFIFO_ENA \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SOURCEFIFO_ENABLE
#define BF_SRC_CFGX_BUFFER_PAIR_ENABLE \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__BUFFER_PAIR_ENABLE
#define BF_SRC_CFGX_NOT_PAUSE_WHEN_EMPTY \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__NOT_PAUSE_WHEN_EMPTY
#define BF_SRC_CFGX_SFIFO_SZ_DOUBLE \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SOURCEFIFO_SIZE_DOUBLE
#define BF_SRC_CFGX_PROCESS_SEQ_ID_VALID \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__PROCESS_SEQ_ID_VALID
#define BF_SRC_CFGX_SAMPLE_CH_MODE \
		AUDIO_AUD_FMM_BF_CTRL_SOURCECH_CFG2__SAMPLE_CH_MODE

#define BF_DST_CFGX_CAP_MODE \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__CAPTURE_MODE
#define BF_DST_CFGX_DFIFO_SZ_DOUBLE \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__DESTFIFO_SIZE_DOUBLE
#define BF_DST_CFGX_NOT_PAUSE_WHEN_FULL \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__NOT_PAUSE_WHEN_FULL
#define BF_DST_CFGX_FCI_ID \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__FCI_CAP_ID_R
#define BF_DST_CFGX_PROC_SEQ_ID_VALID \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__PROCESS_SEQ_ID_VALID
#define BF_DST_CFGX_CAP_ENA \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__CAPTURE_ENABLE
#define BF_DST_CFGX_BUFFER_PAIR_ENABLE \
		AUDIO_AUD_FMM_BF_CTRL_DESTCH_CFG2__BUFFER_PAIR_ENABLE

#define CRMU_GENPLL_PWRON_BG    CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_BG
#define CRMU_GENPLL_PWRON_LDO   CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_LDO
#define CRMU_GENPLL_PWRON_PLL   CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_PLL
#define CRMU_GENPLL_ISO_IN      CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_ISO_IN
#define SPDIF_0_OUT_DITHER_ENA \
		AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL__DITHER_ENA
#define SPDIF_0_OUT_STREAM_ENA \
		AUDIO_AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0__ENA

#define IOP_NCO_NUMERATOR \
		AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_SAMPLE_INC__NUMERATOR_R
#define IOP_NCO_CONTROL_RESET \
		AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL__RESET
#define IOP_NCO_CONTROL_FREE_RUN \
		AUDIO_AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL__FREE_RUN
#define IOP_PLL_0_USER_NDIV_FRAC \
		AUDIO_AUD_FMM_IOP_PLL_0_USER_NDIV__NDIV_FRAC_R
#define IOP_PLL_0_ACTIVE_NDIV_FRAC \
		AUDIO_AUD_FMM_IOP_PLL_0_ACTIVE_NDIV__NDIV_FRAC_R

#define INIT_SSP_REGS(num) { \
		.i2s_stream_cfg = OUT_I2S_ ##num## _STREAM_CFG_OFFSET, \
		.i2s_cap_stream_cfg = IN_I2S_ ##num## _STREAM_CFG_OFFSET, \
		.i2s_cfg = OUT_I2S_ ##num## _CFG_OFFSET, \
		.i2s_cap_cfg = IN_I2S_ ##num## _CFG_OFFSET, \
		.i2s_mclk_cfg = OUT_I2S_ ##num## _MCLK_CFG_OFFSET, \
		.bf_destch_ctrl = BF_DST_CTRL ##num## _OFFSET, \
		.bf_destch_cfg = BF_DST_CFG ##num## _OFFSET, \
		.bf_sourcech_ctrl = BF_SRC_CTRL ##num## _OFFSET, \
		.bf_sourcech_cfg = BF_SRC_CFG ##num## _OFFSET \
}

#define PEGASUS_TDM_DAI_MAX_SLOTS 16

#define MAX_PLAYBACK_PORTS 4
#define MAX_CAPTURE_PORTS 3

#define PEGASUS_SSP_FRAMEBITS_DIV 1

#define SSPMODE_I2S 0
#define SSPMODE_TDM 1

#define PEGASUS_SSP_CLKSRC_PLL      0
#define PEGASUS_SSP_CLKSRC_NCO_0    1
#define PEGASUS_SSP_CLKSRC_NCO_1    2

#define PEGASUS_TDM_RATE \
		(SNDRV_PCM_RATE_8000 | SNDRV_PCM_RATE_16000 | \
		SNDRV_PCM_RATE_32000 | SNDRV_PCM_RATE_44100 | \
		SNDRV_PCM_RATE_48000)

#define PEGASUS_TDM_CFG_VAL 0x88809843

#define TS_LCPLL_CONTROL0_RESET 0x00010000
#define AUDIO_MISC_INIT_VAL 0xc0000c03
#define I2S0_MCLK_ENABLE  0x0000000f
#define I2S1_MCLK_ENABLE  0x000000f0
#define I2S2_MCLK_ENABLE  0x00000f00
#define SPDIF_MCLK_ENABLE 0x00001000

enum ports {
	I2S0 = 0,
	I2S1,
	I2S2,
	SPDIF
};

struct pegasus_ssp_regs {
	uint32_t i2s_stream_cfg;
	uint32_t i2s_cfg;
	uint32_t i2s_cap_stream_cfg;
	uint32_t i2s_cap_cfg;
	uint32_t i2s_mclk_cfg;

	uint32_t bf_destch_ctrl;
	uint32_t bf_destch_cfg;
	uint32_t bf_sourcech_ctrl;
	uint32_t bf_sourcech_cfg;
};

struct pegasus_aio {
	int portnum;
	int mode;
	int slave;        /* 0 = master mode,  1 = slave mode */
	int streams_on;   /* will be 0 if both capture and play are off */
	int channel_grouping;
	int clksrc;

	uint32_t mclk;
	uint32_t lrclk;
	uint32_t bitrate;

	struct pegasus_ssp_regs regs;

	struct ringbuf_regs play_rb_regs;
	struct ringbuf_regs capture_rb_regs;

	void __iomem *audio;
	void __iomem *chip_id;
	void __iomem *asiutop;
	void __iomem *m0_idm_reset;
	void __iomem *lcpll_ctrl;
};

extern int pegasus_ssp_get_mode(struct snd_soc_dai *cpu_dai);
extern int pegasus_ssp_add_pll_tweak_controls(struct snd_soc_pcm_runtime *rtd);

#endif
