# NORTHSTAR2 Platform Support
snd-soc-ns2-objs := ns2-pcm.o
snd-soc-ns2-ssp-objs := ns2-ssp.o

obj-$(CONFIG_SND_SOC_NORTHSTAR2) += snd-soc-ns2.o
obj-$(CONFIG_SND_SOC_NORTHSTAR2_SSP) += snd-soc-ns2-ssp.o

# For NORTHSTAR2 SVK
snd-soc-ns2-svk-machine-objs := ns2_svk-machine.o
obj-$(CONFIG_SND_SOC_NORTHSTAR2_AUDIO_MACHINE) += snd-soc-ns2-svk-machine.o
