/*
 * Copyright (C) 2015, Broadcom Corporation. All Rights Reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef __NS2_SSP_H__
#define __NS2_SSP_H__

#include "ns2-pcm.h"

#define PLL_NDIV_FRACT_MAX  (BIT(20)-1)   /* 20 bits max */

#define I2S_OUT_0_FCI_ID 0x180
#define I2S_OUT_1_FCI_ID 0x181
#define I2S_OUT_2_FCI_ID 0x182

#define CRMU_PLL_AON_CTRL_BASE 0x20

#define AUD_FMM_BF_CTRL_DESTCH_CFG0_REG_BASE 0x100
#define AUD_FMM_BF_CTRL_DESTCH_CFG1_REG_BASE 0x104
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG_BASE 0x108

#define AUD_FMM_BF_CTRL_DESTCH_CTRL0_REG_BASE 0x130
#define AUD_FMM_BF_CTRL_DESTCH_CTRL1_REG_BASE 0x134
#define AUD_FMM_BF_CTRL_DESTCH_CTRL2_REG_BASE 0x138

#define AUD_FMM_BF_CTRL_SOURCECH_CFG0_REG_BASE 0x148
#define AUD_FMM_BF_CTRL_SOURCECH_CFG1_REG_BASE 0x14c
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG_BASE 0x150
#define AUD_FMM_BF_CTRL_SOURCECH_CFG3_REG_BASE 0x154

#define AUD_FMM_BF_CTRL_SOURCECH_CTRL0_REG_BASE 0x1c0
#define AUD_FMM_BF_CTRL_SOURCECH_CTRL1_REG_BASE 0x1c4
#define AUD_FMM_BF_CTRL_SOURCECH_CTRL2_REG_BASE 0x1c8
#define AUD_FMM_BF_CTRL_SOURCECH_CTRL3_REG_BASE 0x1cc

#define AUD_FMM_BF_CTRL_SOURCECH_GRP0_REG_BASE 0x1fc
#define AUD_FMM_BF_CTRL_SOURCECH_GRP1_REG_BASE 0x200
#define AUD_FMM_BF_CTRL_SOURCECH_GRP2_REG_BASE 0x204
#define AUD_FMM_BF_CTRL_SOURCECH_GRP3_REG_BASE 0x208

#define AUD_FMM_IOP_OUT_I2S_0_STREAM_CFG_0_REG_BASE 0xa00
#define AUD_FMM_IOP_OUT_I2S_0_I2S_CFG_REG_BASE      0xa04
#define AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0_REG_BASE   0xa0c

#define AUD_FMM_IOP_OUT_I2S_1_STREAM_CFG_0_REG_BASE 0xa40
#define AUD_FMM_IOP_OUT_I2S_1_I2S_CFG_REG_BASE      0xa44
#define AUD_FMM_IOP_OUT_I2S_1_MCLK_CFG_0_REG_BASE   0xa4c

#define AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG_BASE 0xa80
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG_BASE      0xa84
#define AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0_REG_BASE   0xa8c

#define AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0_REG_BASE     0xac0
#define AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL_REG_BASE       0xac4
#define AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_FORMAT_CFG_REG_BASE 0xad8
#define AUD_FMM_IOP_OUT_SPDIF_0_MCLK_CFG_0_REG_BASE       0xadc

#define AUD_FMM_IOP_PLL_0_MACRO_REG_BASE 0xb00
#define AUD_FMM_IOP_PLL_0_CONTROL_0_REG_BASE 0xb04
#define AUD_FMM_IOP_PLL_0_USER_NDIV_REG_BASE 0xb08
#define AUD_FMM_IOP_PLL_0_USER_MDIV_Ch0_REG_BASE 0xb14
#define AUD_FMM_IOP_PLL_0_USER_MDIV_Ch1_REG_BASE 0xb18
#define AUD_FMM_IOP_PLL_0_USER_MDIV_Ch2_REG_BASE 0xb1c
#define AUD_FMM_IOP_PLL_0_ACTIVE_NDIV_REG_BASE 0xb20
#define AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch0_REG_BASE 0xb30
#define AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch1_REG_BASE 0xb34
#define AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch2_REG_BASE 0xb38
#define AUD_FMM_IOP_PLL_0_RESET_REG_BASE 0xb5c

#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_REG_BASE 0xb80
#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_RATE_RATIO_REG_BASE 0xb84
#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_SAMPLE_INC_REG_BASE 0xb88
#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_PHASE_INC_REG_BASE 0xb8c
#define AUD_FMM_IOP_NCO_1_MCLK_GEN_0_CONTROL_REG_BASE 0xbc0

#define AUD_FMM_IOP_IN_I2S_0_CAP_STREAM_CFG_0_REG_BASE 0xc00
#define AUD_FMM_IOP_IN_I2S_0_I2S_IN_CFG_REG_BASE       0xc04
#define AUD_FMM_IOP_IN_I2S_1_CAP_STREAM_CFG_0_REG_BASE 0xc40
#define AUD_FMM_IOP_IN_I2S_1_I2S_IN_CFG_REG_BASE       0xc44
#define AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_REG_BASE 0xc80
#define AUD_FMM_IOP_IN_I2S_2_I2S_IN_CFG_REG_BASE       0xc84

#define AUD_FMM_IOP_PLL_0_PDIV_BASE 0xb44

/* Bit postion within the various regs */
#define AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0_REG__MCLK_RATE_R 16
#define AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0_REG__PLLCLKSEL_R 0

#define AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG__GROUP_ID_R 20
#define AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG__CHANNEL_GROUPING_R 24
#define AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG__ENA 31

#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SOURCEFIFO_ENABLE 0
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__BUFFER_PAIR_ENABLE 1
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SAMPLE_CH_MODE 2
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SOURCEFIFO_SIZE_DOUBLE 5
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__NOT_PAUSE_WHEN_EMPTY 10
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SFIFO_START_HALFFULL 13
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__BIT_RESOLUTION_R 20
#define AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__PROCESS_SEQ_ID_VALID 31

#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__CAPTURE_ENABLE 0
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__BUFFER_PAIR_ENABLE 1
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__DESTFIFO_SIZE_DOUBLE 2
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__NOT_PAUSE_WHEN_FULL 11
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__FCI_CAP_ID_R 12
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__CAPTURE_MODE 24
#define AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__PROCESS_SEQ_ID_VALID 31

#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__CLOCK_ENABLE 0
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__DATA_ENABLE 1
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__DATA_ALIGNMENT 6
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__BITS_PER_SLOT 13
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__VALID_SLOT_R 14
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__FSYNC_WIDTH_R 18
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__SCLKS_PER_1FS_DIV32_R 26
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__SLAVE_MODE 30
#define AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__TDM_MODE 31

#define AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_REG__CAP_ENA 31
#define AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_REG__CAP_GROUP_ID_R 4

#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_BG 18
#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_LDO 17
#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_PLL 19
#define CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_ISO_IN 16
#define AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL_REG__DITHER_ENA 3
#define AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0_REG__ENA 31

#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_SAMPLE_INC_REG__NUMERATOR_R 16
#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_REG__RESET 12
#define AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_REG__FREE_RUN 4

#define AUD_FMM_IOP_PLL_0_USER_NDIV_REG__NDIV_FRAC_R 10
#define AUD_FMM_IOP_PLL_0_ACTIVE_NDIV_REG__NDIV_FRAC_R 10

/* Shortened and standardized register offsets */
#define CRMU_PLL_AON_CTRL_OFFSET                CRMU_PLL_AON_CTRL_BASE

#define BF_DST_CFG0_OFFSET              AUD_FMM_BF_CTRL_DESTCH_CFG0_REG_BASE
#define BF_DST_CFG1_OFFSET              AUD_FMM_BF_CTRL_DESTCH_CFG1_REG_BASE
#define BF_DST_CFG2_OFFSET              AUD_FMM_BF_CTRL_DESTCH_CFG2_REG_BASE
#define BF_DST_CTRL0_OFFSET             AUD_FMM_BF_CTRL_DESTCH_CTRL0_REG_BASE
#define BF_DST_CTRL1_OFFSET             AUD_FMM_BF_CTRL_DESTCH_CTRL1_REG_BASE
#define BF_DST_CTRL2_OFFSET             AUD_FMM_BF_CTRL_DESTCH_CTRL2_REG_BASE
#define BF_SRC_CFG0_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_CFG0_REG_BASE
#define BF_SRC_CFG1_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_CFG1_REG_BASE
#define BF_SRC_CFG2_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG_BASE
#define BF_SRC_CFG3_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_CFG3_REG_BASE
#define BF_SRC_CTRL0_OFFSET             AUD_FMM_BF_CTRL_SOURCECH_CTRL0_REG_BASE
#define BF_SRC_CTRL1_OFFSET             AUD_FMM_BF_CTRL_SOURCECH_CTRL1_REG_BASE
#define BF_SRC_CTRL2_OFFSET             AUD_FMM_BF_CTRL_SOURCECH_CTRL2_REG_BASE
#define BF_SRC_CTRL3_OFFSET             AUD_FMM_BF_CTRL_SOURCECH_CTRL3_REG_BASE
#define BF_SRC_GRP0_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_GRP0_REG_BASE
#define BF_SRC_GRP1_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_GRP1_REG_BASE
#define BF_SRC_GRP2_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_GRP2_REG_BASE
#define BF_SRC_GRP3_OFFSET              AUD_FMM_BF_CTRL_SOURCECH_GRP3_REG_BASE

#define OUT_I2S_0_CFG_OFFSET    AUD_FMM_IOP_OUT_I2S_0_I2S_CFG_REG_BASE
#define OUT_I2S_1_CFG_OFFSET    AUD_FMM_IOP_OUT_I2S_1_I2S_CFG_REG_BASE
#define OUT_I2S_2_CFG_OFFSET    AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG_BASE

#define OUT_I2S_0_MCLK_CFG_OFFSET AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0_REG_BASE
#define OUT_I2S_1_MCLK_CFG_OFFSET AUD_FMM_IOP_OUT_I2S_1_MCLK_CFG_0_REG_BASE
#define OUT_I2S_2_MCLK_CFG_OFFSET AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0_REG_BASE

#define IOP_PLL_0_MACRO_OFFSET          AUD_FMM_IOP_PLL_0_MACRO_REG_BASE
#define IOP_PLL_0_MDIV_Ch0_OFFSET       AUD_FMM_IOP_PLL_0_USER_MDIV_Ch0_REG_BASE
#define IOP_PLL_0_MDIV_Ch1_OFFSET       AUD_FMM_IOP_PLL_0_USER_MDIV_Ch1_REG_BASE
#define IOP_PLL_0_MDIV_Ch2_OFFSET       AUD_FMM_IOP_PLL_0_USER_MDIV_Ch2_REG_BASE

#define IOP_PLL_0_ACTIVE_MDIV_Ch0_OFFSET \
		AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch0_REG_BASE
#define IOP_PLL_0_ACTIVE_MDIV_Ch1_OFFSET \
		AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch1_REG_BASE
#define IOP_PLL_0_ACTIVE_MDIV_Ch2_OFFSET \
		AUD_FMM_IOP_PLL_0_ACTIVE_MDIV_Ch2_REG_BASE
#define IOP_PLL_0_RESET_OFFSET          AUD_FMM_IOP_PLL_0_RESET_REG_BASE
#define IOP_PLL_0_USER_NDIV_OFFSET AUD_FMM_IOP_PLL_0_USER_NDIV_REG_BASE
#define IOP_PLL_0_ACTIVE_NDIV_OFFSET AUD_FMM_IOP_PLL_0_ACTIVE_NDIV_REG_BASE
#define IOP_PLL_0_CONTROL_OFFSET AUD_FMM_IOP_PLL_0_CONTROL_0_REG_BASE
#define IOP_NCO_0_CONTROL_OFFSET AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_REG_BASE
#define IOP_NCO_1_CONTROL_OFFSET AUD_FMM_IOP_NCO_1_MCLK_GEN_0_CONTROL_REG_BASE

#define IN_I2S_0_CFG_OFFSET   AUD_FMM_IOP_IN_I2S_0_I2S_IN_CFG_REG_BASE
#define IN_I2S_1_CFG_OFFSET   AUD_FMM_IOP_IN_I2S_1_I2S_IN_CFG_REG_BASE
#define IN_I2S_2_CFG_OFFSET   AUD_FMM_IOP_IN_I2S_2_I2S_IN_CFG_REG_BASE

#define SPDIF_CTRL_OFFSET \
			AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL_REG_BASE
#define SPDIF_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0_REG_BASE
#define SPDIF_FORMAT_CFG_OFFSET \
			AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_FORMAT_CFG_REG_BASE
#define SPDIF_MCLK_CFG_OFFSET \
			AUD_FMM_IOP_OUT_SPDIF_0_MCLK_CFG_0_REG_BASE

#define IN_I2S_0_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_IN_I2S_0_CAP_STREAM_CFG_0_REG_BASE
#define IN_I2S_1_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_IN_I2S_1_CAP_STREAM_CFG_0_REG_BASE
#define IN_I2S_2_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_REG_BASE

#define OUT_I2S_0_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_OUT_I2S_0_STREAM_CFG_0_REG_BASE
#define OUT_I2S_1_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_OUT_I2S_1_STREAM_CFG_0_REG_BASE
#define OUT_I2S_2_STREAM_CFG_OFFSET \
			AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG_BASE

/* Shortened and standardized register bit definitions */

#define I2S_OUT_MCLKRATE_SHIFT \
		AUD_FMM_IOP_OUT_I2S_2_MCLK_CFG_0_REG__MCLK_RATE_R
#define I2S_OUT_MCLKRATE_MASK  (0xF << I2S_OUT_MCLKRATE_SHIFT)

#define I2S_OUT_PLLCLKSEL_SHIFT  \
		AUD_FMM_IOP_OUT_I2S_0_MCLK_CFG_0_REG__PLLCLKSEL_R
#define I2S_OUT_PLLCLKSEL_MASK  (0xF << I2S_OUT_PLLCLKSEL_SHIFT)

#define I2S_OUT_STREAM_ENA \
		AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG__ENA
#define I2S_OUT_STREAM_CFG_GROUP_ID \
		AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG__GROUP_ID_R
#define I2S_OUT_STREAM_CFG_CHANNEL_GROUPING \
		AUD_FMM_IOP_OUT_I2S_2_STREAM_CFG_0_REG__CHANNEL_GROUPING_R

#define I2S_IN_STREAM_CFG_CAP_ENA \
		AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_REG__CAP_ENA
#define I2S_IN_STREAM_CFG_0_GROUP_ID \
		AUD_FMM_IOP_IN_I2S_2_CAP_STREAM_CFG_0_REG__CAP_GROUP_ID_R

#define I2S_OUT_CFGX_CLK_ENA \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__CLOCK_ENABLE
#define I2S_OUT_CFGX_DATA_ENABLE \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__DATA_ENABLE
#define I2S_OUT_CFGX_TDM_MODE \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__TDM_MODE
#define I2S_OUT_CFGX_SLAVE_MODE \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__SLAVE_MODE
#define I2S_OUT_CFGX_FSYNC_WIDTH \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__FSYNC_WIDTH_R
#define I2S_OUT_CFGX_VALID_SLOT \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__VALID_SLOT_R
#define I2S_OUT_CFGX_BITS_PER_SLOT \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__BITS_PER_SLOT
#define I2S_OUT_CFGX_DATA_ALIGNMENT \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__DATA_ALIGNMENT
#define I2S_OUT_CFGX_SCLKS_PER_1FS_DIV32 \
		AUD_FMM_IOP_OUT_I2S_2_I2S_CFG_REG__SCLKS_PER_1FS_DIV32_R

#define BF_SRC_CFGX_BIT_RES \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__BIT_RESOLUTION_R
#define BF_SRC_CFGX_SFIFO_ENA \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SOURCEFIFO_ENABLE
#define BF_SRC_CFGX_BUFFER_PAIR_ENABLE \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__BUFFER_PAIR_ENABLE
#define BF_SRC_CFGX_NOT_PAUSE_WHEN_EMPTY \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__NOT_PAUSE_WHEN_EMPTY
#define BF_SRC_CFGX_SFIFO_SZ_DOUBLE \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SOURCEFIFO_SIZE_DOUBLE
#define BF_SRC_CFGX_PROCESS_SEQ_ID_VALID \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__PROCESS_SEQ_ID_VALID
#define BF_SRC_CFGX_SAMPLE_CH_MODE \
		AUD_FMM_BF_CTRL_SOURCECH_CFG2_REG__SAMPLE_CH_MODE

#define BF_DST_CFGX_CAP_MODE \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__CAPTURE_MODE
#define BF_DST_CFGX_DFIFO_SZ_DOUBLE \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__DESTFIFO_SIZE_DOUBLE
#define BF_DST_CFGX_NOT_PAUSE_WHEN_FULL \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__NOT_PAUSE_WHEN_FULL
#define BF_DST_CFGX_FCI_ID \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__FCI_CAP_ID_R
#define BF_DST_CFGX_PROC_SEQ_ID_VALID \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__PROCESS_SEQ_ID_VALID
#define BF_DST_CFGX_CAP_ENA \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__CAPTURE_ENABLE
#define BF_DST_CFGX_BUFFER_PAIR_ENABLE \
		AUD_FMM_BF_CTRL_DESTCH_CFG2_REG__BUFFER_PAIR_ENABLE

#define CRMU_GENPLL_PWRON_BG    CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_BG
#define CRMU_GENPLL_PWRON_LDO   CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_LDO
#define CRMU_GENPLL_PWRON_PLL   CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_PWRON_PLL
#define CRMU_GENPLL_ISO_IN      CRMU_PLL_AON_CTRL__ASIU_AUDIO_GENPLL_ISO_IN
#define SPDIF_0_OUT_DITHER_ENA \
		AUD_FMM_IOP_OUT_SPDIF_0_SPDIF_CTRL_REG__DITHER_ENA
#define SPDIF_0_OUT_STREAM_ENA \
		AUD_FMM_IOP_OUT_SPDIF_0_STREAM_CFG_0_REG__ENA

#define IOP_NCO_NUMERATOR \
		AUD_FMM_IOP_NCO_0_MCLK_GEN_0_SAMPLE_INC_REG__NUMERATOR_R
#define IOP_NCO_CONTROL_RESET \
		AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_REG__RESET
#define IOP_NCO_CONTROL_FREE_RUN \
		AUD_FMM_IOP_NCO_0_MCLK_GEN_0_CONTROL_REG__FREE_RUN
#define IOP_PLL_0_USER_NDIV_FRAC \
		AUD_FMM_IOP_PLL_0_USER_NDIV_REG__NDIV_FRAC_R
#define IOP_PLL_0_ACTIVE_NDIV_FRAC \
		AUD_FMM_IOP_PLL_0_ACTIVE_NDIV_REG__NDIV_FRAC_R

#define INIT_SSP_REGS(num) { \
		.i2s_stream_cfg = OUT_I2S_ ##num## _STREAM_CFG_OFFSET, \
		.i2s_cap_stream_cfg = IN_I2S_ ##num## _STREAM_CFG_OFFSET, \
		.i2s_cfg = OUT_I2S_ ##num## _CFG_OFFSET, \
		.i2s_cap_cfg = IN_I2S_ ##num## _CFG_OFFSET, \
		.i2s_mclk_cfg = OUT_I2S_ ##num## _MCLK_CFG_OFFSET, \
		.bf_destch_ctrl = BF_DST_CTRL ##num## _OFFSET, \
		.bf_destch_cfg = BF_DST_CFG ##num## _OFFSET, \
		.bf_sourcech_ctrl = BF_SRC_CTRL ##num## _OFFSET, \
		.bf_sourcech_cfg = BF_SRC_CFG ##num## _OFFSET \
}

#define NS2_TDM_DAI_MAX_SLOTS 16

#define MAX_PLAYBACK_PORTS 4
#define MAX_CAPTURE_PORTS 3

#define NS2_SSP_FRAMEBITS_DIV 1

#define SSPMODE_I2S 0
#define SSPMODE_TDM 1

#define NS2_SSP_CLKSRC_PLL      0
#define NS2_SSP_CLKSRC_NCO_0    1
#define NS2_SSP_CLKSRC_NCO_1    2

#define NS2_TDM_RATE \
		(SNDRV_PCM_RATE_8000 | SNDRV_PCM_RATE_16000 | \
		SNDRV_PCM_RATE_32000 | SNDRV_PCM_RATE_44100 | \
		SNDRV_PCM_RATE_48000)

#define NS2_TDM_CFG_VAL 0x88809843

enum ports {
	I2S0 = 0,
	I2S1,
	I2S2,
	SPDIF
};

struct ns2_ssp_regs {
	uint32_t i2s_stream_cfg;
	uint32_t i2s_cfg;
	uint32_t i2s_cap_stream_cfg;
	uint32_t i2s_cap_cfg;
	uint32_t i2s_mclk_cfg;

	uint32_t bf_destch_ctrl;
	uint32_t bf_destch_cfg;
	uint32_t bf_sourcech_ctrl;
	uint32_t bf_sourcech_cfg;
};

struct ns2_aio {
	int portnum;
	int mode;
	int slave;        /* 0 = master mode,  1 = slave mode */
	int streams_on;   /* will be 0 if both capture and play are off */
	int channel_grouping;
	int clksrc;

	uint32_t mclk;
	uint32_t lrclk;
	uint32_t bitrate;

	struct ns2_ssp_regs regs;

	struct ringbuf_regs play_rb_regs;
	struct ringbuf_regs capture_rb_regs;

	void __iomem *audio;
	void __iomem *crmudru;
	void __iomem *asiutop;
	void __iomem *m0_idm_reset;
};

extern int ns2_ssp_get_mode(struct snd_soc_dai *cpu_dai);
extern int ns2_ssp_add_pll_tweak_controls(struct snd_soc_pcm_runtime *rtd);

#endif
