/*
 * Copyright (C) 2015, Broadcom Corporation. All Rights Reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */
#ifndef __NS2_PCM_H__
#define __NS2_PCM_H__

/* These are offsets necessary to access the various audio block regs.
 * The names used here are how they appear in the datasheets, etc.
 * Some of these names are very long which makes writing code to fit within
 * the 80 column constraint difficult. Therefore, many of these defines
 * are redefined with shorter versions below, these are the versions
 * we will be using in the code.
 */
#define AUD_INTH_R5F_STATUS_REG_BASE 0x040
#define AUD_INTH_R5F_CLEAR_REG_BASE 0x048
#define AUD_INTH_R5F_MASK_SET_REG_BASE 0x050
#define AUD_INTH_R5F_MASK_CLEAR_REG_BASE 0x054

#define AUD_FMM_BF_CTRL_REARM_FREE_MARK_REG_BASE 0x344
#define AUD_FMM_BF_CTRL_REARM_FULL_MARK_REG_BASE 0x348

/* Ring Buffer Ctrl Regs --- Start */
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_RDADDR_REG_BASE 0x500
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_RDADDR_REG_BASE 0x518
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_RDADDR_REG_BASE 0x530
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_RDADDR_REG_BASE 0x548
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_RDADDR_REG_BASE 0x560
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_RDADDR_REG_BASE 0x578
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_RDADDR_REG_BASE 0x590

#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_BASEADDR_REG_BASE 0x508
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_BASEADDR_REG_BASE 0x520
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_BASEADDR_REG_BASE 0x538
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_BASEADDR_REG_BASE 0x550
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_BASEADDR_REG_BASE 0x568
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_BASEADDR_REG_BASE 0x580
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_BASEADDR_REG_BASE 0x598

#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_WRADDR_REG_BASE 0x5c4
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_WRADDR_REG_BASE 0x5dc
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_WRADDR_REG_BASE 0x5f4
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_WRADDR_REG_BASE 0x60c
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_WRADDR_REG_BASE 0x624
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_WRADDR_REG_BASE 0x63c

#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_RDADDR_REG_BASE 0x5c0
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_RDADDR_REG_BASE 0x5d8
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_RDADDR_REG_BASE 0x5f0
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_RDADDR_REG_BASE 0x608
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_RDADDR_REG_BASE 0x620
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_RDADDR_REG_BASE 0x638

#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_ENDADDR_REG_BASE 0x50c
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_ENDADDR_REG_BASE 0x524
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_ENDADDR_REG_BASE 0x53c
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_ENDADDR_REG_BASE 0x554
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_ENDADDR_REG_BASE 0x56c
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_ENDADDR_REG_BASE 0x584
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_ENDADDR_REG_BASE 0x59c

#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_ENDADDR_REG_BASE 0x5cc
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_ENDADDR_REG_BASE 0x5e4
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_ENDADDR_REG_BASE 0x5fc
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_ENDADDR_REG_BASE 0x614
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_ENDADDR_REG_BASE 0x62c
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_ENDADDR_REG_BASE 0x644

#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_WRADDR_REG_BASE 0x504
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_WRADDR_REG_BASE 0x51c
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_WRADDR_REG_BASE 0x534
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_WRADDR_REG_BASE 0x54c
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_WRADDR_REG_BASE 0x564
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_WRADDR_REG_BASE 0x57c
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_WRADDR_REG_BASE 0x594

#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_BASEADDR_REG_BASE 0x640
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_BASEADDR_REG_BASE 0x628
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_BASEADDR_REG_BASE 0x610
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_BASEADDR_REG_BASE 0x5f8
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_BASEADDR_REG_BASE 0x5e0
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_BASEADDR_REG_BASE 0x5c8

#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_FREE_MARK_REG_BASE 0x5a0
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_FREE_MARK_REG_BASE 0x588
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_FREE_MARK_REG_BASE 0x570
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_FREE_MARK_REG_BASE 0x558
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_FREE_MARK_REG_BASE 0x540
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_FREE_MARK_REG_BASE 0x528
#define AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_FREE_MARK_REG_BASE 0x510

#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_FULL_MARK_REG_BASE 0x5d0
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_FULL_MARK_REG_BASE 0x5e8
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_FULL_MARK_REG_BASE 0x600
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_FULL_MARK_REG_BASE 0x618
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_FULL_MARK_REG_BASE 0x630
#define AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_FULL_MARK_REG_BASE 0x648
/* Ring Buffer Ctrl Regs --- End */

/* Error Status Regs --- Start */
#define AUD_FMM_BF_ESR_ESR0_STATUS_REG_BASE 0x900
#define AUD_FMM_BF_ESR_ESR1_STATUS_REG_BASE 0x918
#define AUD_FMM_BF_ESR_ESR2_STATUS_REG_BASE 0x930
#define AUD_FMM_BF_ESR_ESR3_STATUS_REG_BASE 0x948
#define AUD_FMM_BF_ESR_ESR4_STATUS_REG_BASE 0x960

#define AUD_FMM_BF_ESR_ESR0_STATUS_CLEAR_REG_BASE 0x908
#define AUD_FMM_BF_ESR_ESR1_STATUS_CLEAR_REG_BASE 0x920
#define AUD_FMM_BF_ESR_ESR2_STATUS_CLEAR_REG_BASE 0x938
#define AUD_FMM_BF_ESR_ESR3_STATUS_CLEAR_REG_BASE 0x950
#define AUD_FMM_BF_ESR_ESR4_STATUS_CLEAR_REG_BASE 0x968

#define AUD_FMM_BF_ESR_ESR0_MASK_SET_REG_BASE 0x910
#define AUD_FMM_BF_ESR_ESR1_MASK_SET_REG_BASE 0x928
#define AUD_FMM_BF_ESR_ESR2_MASK_SET_REG_BASE 0x940
#define AUD_FMM_BF_ESR_ESR3_MASK_SET_REG_BASE 0x958
#define AUD_FMM_BF_ESR_ESR4_MASK_SET_REG_BASE 0x970

#define AUD_FMM_BF_ESR_ESR0_MASK_CLEAR_REG_BASE 0x914
#define AUD_FMM_BF_ESR_ESR1_MASK_CLEAR_REG_BASE 0x92c
#define AUD_FMM_BF_ESR_ESR2_MASK_CLEAR_REG_BASE 0x944
#define AUD_FMM_BF_ESR_ESR3_MASK_CLEAR_REG_BASE 0x95c
#define AUD_FMM_BF_ESR_ESR4_MASK_CLEAR_REG_BASE 0x974

#define AUD_FMM_BF_ESR_ESR0_MASK_REG_BASE 0x90c
#define AUD_FMM_BF_ESR_ESR1_MASK_REG_BASE 0x924
#define AUD_FMM_BF_ESR_ESR2_MASK_REG_BASE 0x93c
#define AUD_FMM_BF_ESR_ESR3_MASK_REG_BASE 0x954
#define AUD_FMM_BF_ESR_ESR4_MASK_REG_BASE 0x96c
/* Error Status Regs --- End */

#define INTH_R5F_STATUS_OFFSET          AUD_INTH_R5F_STATUS_REG_BASE
#define INTH_R5F_MASK_SET_OFFSET        AUD_INTH_R5F_MASK_SET_REG_BASE
#define INTH_R5F_CLEAR_OFFSET           AUD_INTH_R5F_CLEAR_REG_BASE
#define INTH_R5F_MASK_CLEAR_OFFSET      AUD_INTH_R5F_MASK_CLEAR_REG_BASE

#define BF_REARM_FREE_MARK_OFFSET       AUD_FMM_BF_CTRL_REARM_FREE_MARK_REG_BASE
#define BF_REARM_FULL_MARK_OFFSET       AUD_FMM_BF_CTRL_REARM_FULL_MARK_REG_BASE


#define SRC_RBUF_0_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_RDADDR_REG_BASE
#define SRC_RBUF_1_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_RDADDR_REG_BASE
#define SRC_RBUF_2_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_RDADDR_REG_BASE
#define SRC_RBUF_3_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_RDADDR_REG_BASE
#define SRC_RBUF_4_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_RDADDR_REG_BASE
#define SRC_RBUF_5_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_RDADDR_REG_BASE
#define SRC_RBUF_6_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_RDADDR_REG_BASE
#define SRC_RBUF_0_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_BASEADDR_REG_BASE
#define SRC_RBUF_1_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_BASEADDR_REG_BASE
#define SRC_RBUF_2_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_BASEADDR_REG_BASE
#define SRC_RBUF_3_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_BASEADDR_REG_BASE
#define SRC_RBUF_4_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_BASEADDR_REG_BASE
#define SRC_RBUF_5_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_BASEADDR_REG_BASE
#define SRC_RBUF_6_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_BASEADDR_REG_BASE
#define DST_RBUF_0_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_WRADDR_REG_BASE
#define DST_RBUF_1_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_WRADDR_REG_BASE
#define DST_RBUF_2_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_WRADDR_REG_BASE
#define DST_RBUF_3_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_WRADDR_REG_BASE
#define DST_RBUF_4_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_WRADDR_REG_BASE
#define DST_RBUF_5_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_WRADDR_REG_BASE
#define DST_RBUF_0_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_RDADDR_REG_BASE
#define DST_RBUF_1_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_RDADDR_REG_BASE
#define DST_RBUF_2_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_RDADDR_REG_BASE
#define DST_RBUF_3_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_RDADDR_REG_BASE
#define DST_RBUF_4_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_RDADDR_REG_BASE
#define DST_RBUF_5_RDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_RDADDR_REG_BASE
#define SRC_RBUF_0_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_ENDADDR_REG_BASE
#define SRC_RBUF_1_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_ENDADDR_REG_BASE
#define SRC_RBUF_2_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_ENDADDR_REG_BASE
#define SRC_RBUF_3_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_ENDADDR_REG_BASE
#define SRC_RBUF_4_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_ENDADDR_REG_BASE
#define SRC_RBUF_5_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_ENDADDR_REG_BASE
#define SRC_RBUF_6_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_ENDADDR_REG_BASE
#define DST_RBUF_0_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_ENDADDR_REG_BASE
#define DST_RBUF_1_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_ENDADDR_REG_BASE
#define DST_RBUF_2_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_ENDADDR_REG_BASE
#define DST_RBUF_3_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_ENDADDR_REG_BASE
#define DST_RBUF_4_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_ENDADDR_REG_BASE
#define DST_RBUF_5_ENDADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_ENDADDR_REG_BASE
#define SRC_RBUF_0_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_WRADDR_REG_BASE
#define SRC_RBUF_1_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_WRADDR_REG_BASE
#define SRC_RBUF_2_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_WRADDR_REG_BASE
#define SRC_RBUF_3_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_WRADDR_REG_BASE
#define SRC_RBUF_4_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_WRADDR_REG_BASE
#define SRC_RBUF_5_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_WRADDR_REG_BASE
#define SRC_RBUF_6_WRADDR_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_WRADDR_REG_BASE
#define DST_RBUF_5_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_BASEADDR_REG_BASE
#define DST_RBUF_4_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_BASEADDR_REG_BASE
#define DST_RBUF_3_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_BASEADDR_REG_BASE
#define DST_RBUF_2_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_BASEADDR_REG_BASE
#define DST_RBUF_1_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_BASEADDR_REG_BASE
#define DST_RBUF_0_BASEADDR_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_BASEADDR_REG_BASE
#define SRC_RBUF_6_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_6_FREE_MARK_REG_BASE
#define SRC_RBUF_5_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_5_FREE_MARK_REG_BASE
#define SRC_RBUF_4_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_4_FREE_MARK_REG_BASE
#define SRC_RBUF_3_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_3_FREE_MARK_REG_BASE
#define SRC_RBUF_2_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_2_FREE_MARK_REG_BASE
#define SRC_RBUF_1_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_1_FREE_MARK_REG_BASE
#define SRC_RBUF_0_FREE_MARK_OFFSET \
			AUD_FMM_BF_CTRL_SOURCECH_RINGBUF_0_FREE_MARK_REG_BASE
#define DST_RBUF_0_FULL_MARK_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_0_FULL_MARK_REG_BASE
#define DST_RBUF_1_FULL_MARK_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_1_FULL_MARK_REG_BASE
#define DST_RBUF_2_FULL_MARK_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_2_FULL_MARK_REG_BASE
#define DST_RBUF_3_FULL_MARK_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_3_FULL_MARK_REG_BASE
#define DST_RBUF_4_FULL_MARK_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_4_FULL_MARK_REG_BASE
#define DST_RBUF_5_FULL_MARK_OFFSET \
			AUD_FMM_BF_CTRL_DESTCH_RINGBUF_5_FULL_MARK_REG_BASE

#define ESR0_STATUS_OFFSET      AUD_FMM_BF_ESR_ESR0_STATUS_REG_BASE
#define ESR1_STATUS_OFFSET      AUD_FMM_BF_ESR_ESR1_STATUS_REG_BASE
#define ESR2_STATUS_OFFSET      AUD_FMM_BF_ESR_ESR2_STATUS_REG_BASE
#define ESR3_STATUS_OFFSET      AUD_FMM_BF_ESR_ESR3_STATUS_REG_BASE
#define ESR4_STATUS_OFFSET      AUD_FMM_BF_ESR_ESR4_STATUS_REG_BASE
#define ESR0_STATUS_CLR_OFFSET  AUD_FMM_BF_ESR_ESR0_STATUS_CLEAR_REG_BASE
#define ESR1_STATUS_CLR_OFFSET  AUD_FMM_BF_ESR_ESR1_STATUS_CLEAR_REG_BASE
#define ESR2_STATUS_CLR_OFFSET  AUD_FMM_BF_ESR_ESR2_STATUS_CLEAR_REG_BASE
#define ESR3_STATUS_CLR_OFFSET  AUD_FMM_BF_ESR_ESR3_STATUS_CLEAR_REG_BASE
#define ESR4_STATUS_CLR_OFFSET  AUD_FMM_BF_ESR_ESR4_STATUS_CLEAR_REG_BASE
#define ESR0_MASK_SET_OFFSET    AUD_FMM_BF_ESR_ESR0_MASK_SET_REG_BASE
#define ESR1_MASK_SET_OFFSET    AUD_FMM_BF_ESR_ESR1_MASK_SET_REG_BASE
#define ESR2_MASK_SET_OFFSET    AUD_FMM_BF_ESR_ESR2_MASK_SET_REG_BASE
#define ESR3_MASK_SET_OFFSET    AUD_FMM_BF_ESR_ESR3_MASK_SET_REG_BASE
#define ESR4_MASK_SET_OFFSET    AUD_FMM_BF_ESR_ESR4_MASK_SET_REG_BASE
#define ESR0_MASK_CLR_OFFSET    AUD_FMM_BF_ESR_ESR0_MASK_CLEAR_REG_BASE
#define ESR1_MASK_CLR_OFFSET    AUD_FMM_BF_ESR_ESR1_MASK_CLEAR_REG_BASE
#define ESR2_MASK_CLR_OFFSET    AUD_FMM_BF_ESR_ESR2_MASK_CLEAR_REG_BASE
#define ESR3_MASK_CLR_OFFSET    AUD_FMM_BF_ESR_ESR3_MASK_CLEAR_REG_BASE
#define ESR4_MASK_CLR_OFFSET    AUD_FMM_BF_ESR_ESR4_MASK_CLEAR_REG_BASE
#define ESR0_MASK_STATUS_OFFSET AUD_FMM_BF_ESR_ESR0_MASK_REG_BASE
#define ESR1_MASK_STATUS_OFFSET AUD_FMM_BF_ESR_ESR1_MASK_REG_BASE
#define ESR2_MASK_STATUS_OFFSET AUD_FMM_BF_ESR_ESR2_MASK_REG_BASE
#define ESR3_MASK_STATUS_OFFSET AUD_FMM_BF_ESR_ESR3_MASK_REG_BASE
#define ESR4_MASK_STATUS_OFFSET AUD_FMM_BF_ESR_ESR4_MASK_REG_BASE

struct ringbuf_regs {
	unsigned rdaddr;
	unsigned wraddr;
	unsigned baseaddr;
	unsigned endaddr;
	unsigned fmark;   /* freemark for play, fullmark for caputure */
	unsigned period_bytes;
	unsigned buf_size;
};

#define RINGBUF_REG_PLAYBACK(num) ((struct ringbuf_regs) { \
	.rdaddr = SRC_RBUF_ ##num## _RDADDR_OFFSET, \
	.wraddr = SRC_RBUF_ ##num## _WRADDR_OFFSET, \
	.baseaddr = SRC_RBUF_ ##num## _BASEADDR_OFFSET, \
	.endaddr = SRC_RBUF_ ##num## _ENDADDR_OFFSET, \
	.fmark = SRC_RBUF_ ##num## _FREE_MARK_OFFSET, \
	.period_bytes = 0, \
	.buf_size = 0, \
})

#define RINGBUF_REG_CAPTURE(num) ((struct ringbuf_regs)  { \
	.rdaddr = DST_RBUF_ ##num## _RDADDR_OFFSET, \
	.wraddr = DST_RBUF_ ##num## _WRADDR_OFFSET, \
	.baseaddr = DST_RBUF_ ##num## _BASEADDR_OFFSET, \
	.endaddr = DST_RBUF_ ##num## _ENDADDR_OFFSET, \
	.fmark = DST_RBUF_ ##num## _FULL_MARK_OFFSET, \
	.period_bytes = 0, \
	.buf_size = 0, \
})
#endif
